twilio/twilio-php

Services/Twilio/Twiml.php
=> Fixes #201

docs/usage/token-generation.rst
=> Fix broken capability token link

LICENSE, Makefile, docs/read_the_docs/conf.py
Only affects LICENSE, Makefile, and RTD docs
=> Update repo author to 'Twilio'

README.md
Also updated reference to console.
=> Updated the first snippet, so that Google results are meaningful. 

Twilio/Http/CurlClient.php, Twilio/Tests/Unit/Http/CurlClientTest.php
Updates tests for $options injection behavior
=> Add $options to the CurlClient

README.md
Update README file code examples to use the latest library interface.
=> Update README file examples to use the latest library interface.

Twilio/Jwt/Grants/TaskRouterGrant.php, Twilio/Tests/Unit/Jwt/AccessTokenTest.php
Migrating TaskRouter to Access Tokens. Adding a TaskRouter grant.
=> Adding TaskRouterGrant

.gitattributes
This is cleaning up the files downloaded when using composer.
This is a proposal, and I have only done some simple tests on this (making calls, and playing with XML where it all works.
This fixes #463
=> Added .gitattributes to cleanup the composer

Twilio/Security/RequestValidator.php, Twilio/Tests/Unit/RequestValidatorTest.php
This PR:
- Adds testing for RequestValidator.php (🎉)
- Adds body validation for requests that contain non-form bodies
=> Add a request body validator

README.md
Minor doc update as the XML closing tag is incorrect.
=> Fix invalid generated XML in README

README.md
Thanks to @NinoSkopac for proposing this change in #501. Creating a new PR that merges the two suggestions together.
=> Include composer require command

Twilio/Http/GuzzleClient.php, Twilio/Tests/Unit/Http/GuzzleClientTest.php, composer.json, composer.lock
Added an HTTP Client for Guzzle
> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.
=> Added Guzzle HTTP client

Twilio/Rest/Lookups/V1/PhoneNumberInstance.php, Twilio/Rest/Trunking/V1/Trunk/PhoneNumberInstance.php
=> Correct the 'array' type hint for a few resource instance properties

CONTRIBUTING.md, Dockerfile-dev, Makefile
Please see the usage documentation added to CONTRIBUTING.md
=> Adds local dockerized tests for configurable PHP versions

src/Twilio/autoload.php
=> Put back the parent directory directive in 'autoload'

src/Twilio/Http/CurlClient.php
=> Fix curl client fails through squid proxy

README.md
=> Notice of BREAKING CHANGE for PHP version 5

Makefile, composer.json, phpdox.xml
apigen is not compatible with PHP 7.2+: https://github.com/ApiGen/ApiGen/issues/1039
=> fix: migrate to phpdox for source code doc generation

src/Twilio/Exceptions/RestException.php, src/Twilio/Page.php, src/Twilio/Version.php, tests/Twilio/Unit/VersionTest.php
Add a new property named `details` to RestException. Details is returned by selective apis to populate extra information about errors.
The Studio V2 flow api will be returning extra details with flow validation errors.
=> feat: add details to rest exception

src/Twilio/InstanceResource.php, tests/Twilio/Unit/InstanceResourceTest.php
=> feat: add __isset magic method for resource instance properties

src/Twilio/Http/CurlClient.php
Remove undefined variable and close an open file pointer in `Twilio\Http\CurlClient`. Close #518
=> fix: Remove undefined variable and close an open file pointer

composer.json
Hi,
We have recently tagged a new version 7 of guzzle.
https://github.com/guzzle/guzzle/releases/tag/7.0.0
🎉
=> chore: Add Guzzle 7

src/Twilio/Rest/Studio.php
https://issues.corp.twilio.com/browse/DI-702
=> fix: shortcut syntax for new non-GA versions

.travis.yml, README.md
A short description of what this PR does.
=> test: Travis test for PHP8

src/Twilio/Http/GuzzleClient.php
Fix for https://travis-ci.com/github/twilio/twilio-php/jobs/520652856
=> fix: replace deprecated method build_query with Query::build

.github/workflows/publish_docker.yml, .github/workflows/test.yml
[Test Run](https://github.com/shwetha-manvinkurke/twilio-php/actions/runs/1422259072)
=> fix: docker publish issues

.github/workflows/test.yml, Makefile
To enable running releases on admiral hosts
=> chore: remove install as a dependency of test

Makefile, composer.json, tests/phpunit.xml
This is a patch to unblock other dependency work.
=> fix: install and remove phpdox as required

UPGRADE.md
Jira:[DI-1492](https://issues.corp.twilio.com/browse/DI-1492)
=> docs: add upgrade guide for Php 5.x to 6.x

src/Twilio/Rest/Client.php, tests/Twilio/Unit/Rest/ClientTest.php
Link to JIRA ticket: https://issues.corp.twilio.com/browse/DI-1567
=> chore: update user agent string for twilio-php

sonar-project.properties
Internal Jira Link: [DI-2132](https://issues.corp.twilio.com/browse/DI-2132)
=> test: increase code coverage for sonar analysis

src/Twilio/Security/RequestValidator.php, tests/Twilio/Unit/RequestValidatorTest.php
Fixes https://github.com/twilio/twilio-php/issues/744
=> fix: support duplicate query param values

src/Twilio/Rest/Accounts.php, src/Twilio/Rest/Conversations.php
Base file name was set singular for some files, had to be plural.
=> fix: base file name

.github/workflows/pr-lint.yml, .github/workflows/test-and-deploy.yml, CHANGES.md, src/Twilio/TwiML/Voice/SsmlSayAs.php, src/Twilio/VersionInfo.php
Bringing latest changes from main branch into rc-branch.
=> chore: sync up with main branch

src/Twilio/Base/BaseClient.php, src/Twilio/Base/PhoneNumberCapabilities.php, src/Twilio/Deserialize.php, tests/Twilio/ClusterTest.php, tests/Twilio/Unit/DeserializeTest.php
=> chore: remove code smells

example/call.php, example/incomingPhoneNumber.php, example/message.php, example/record.php, example/signingKey.php, example/trunk.php, example/twiML.php, src/Twilio/Rest/Bulkexports.php, tests/Twilio/Unit/TwiML/Voice/GatherTest.php, tests/Twilio/Unit/TwiML/VoiceResponseTest.php
- Add php examples to make calls to some of the common apis.
- bring back Twiml voice and twiml tests
- correct classname for 'BulkexportsBase'
=> chore: add examples for calling common apis

src/Twilio/VersionInfo.php, tests/Twilio/Unit/Rest/ClientTest.php
- Set correct patch version.
- Add back Client Tests 
=> fix: correct version

src/Twilio/Base/BaseClient.php, src/Twilio/Rest/FlexApi.php, src/Twilio/Rest/Taskrouter.php, tests/Twilio/Unit/Rest/ClientTest.php
- Drop shortcuts for removed APIs. Ref: [here](https://github.com/twilio/twilio-php/commit/56ffc60eb0b82263fc207ac5c6292b0c90022085#diff-0c356269908fc04e17f39c7dfa5dc511fe3a83c09ddb1ac88f86d708c2f06fbcL145)
- Fix casing for TaskrouterBase
- Add Api property to BaseClient
=> fix: drop removed APIs

composer.json
Some methods have been deprecated and removed in PhpUnit 10 including `assertObjectNotHasAttribute()`, `assertRegExp()`
Replacing these methods with their alternatives will lead to test failures for Php 7.2 because PHP 7.2 requires PhpUnit 8.5 and the alternative `assertMatchesRegularExpression()` for `assertRegExp()` is not supported by phpUnit 8.5
=> fix: test failures for PhpUnit >=10

src/Twilio/Base/BaseClient.php
A short description of what this PR does.
Update ValidateSslCertificate method with security testing method
=> fix: Update ValidateSslCertificate method with security testing method

src/Twilio/Serialize.php, tests/Twilio/Unit/SerializeTest.php
The booleanToString() was converting boolean true to "True" which should be "true". Similarly for false.
=> fix: corrected booleanToString function

CHANGES.md, UPGRADE.md, example/messaging_bulk.php
Added example file on usage of bulk messaging api
=> feat!: MVR preparation

.github/workflows/test-and-deploy.yml, README.md
Adding support for PHP 8.2 and 8.3
=> chore: adding support for PHP 8.2 and 8.3

README.md
=> docs: updated readme with page example

src/Twilio/Http/CurlClient.php, src/Twilio/Http/GuzzleClient.php, tests/Twilio/Unit/Http/CurlClientTest.php
ContentType is required in POST and PUT methods. Adding the support for PUT.
=> chore: adding support for put

.github/workflows/test-and-deploy.yml, src/Twilio/Base/BaseClient.php, src/Twilio/Domain.php, src/Twilio/Http/Client.php, src/Twilio/Http/CurlClient.php, src/Twilio/Http/File.php, src/Twilio/Http/GuzzleClient.php, src/Twilio/Jwt/AccessToken.php, src/Twilio/Jwt/JWT.php, src/Twilio/Jwt/TaskRouter/CapabilityToken.php, src/Twilio/Jwt/TaskRouter/TaskQueueCapability.php, src/Twilio/Jwt/TaskRouter/WorkerCapability.php, src/Twilio/Jwt/TaskRouter/WorkspaceCapability.php, src/Twilio/Page.php, src/Twilio/TaskRouter/WorkflowRule.php, src/Twilio/TaskRouter/WorkflowRuleTarget.php, src/Twilio/TwiML/GenericNode.php, src/Twilio/TwiML/TwiML.php, src/Twilio/Values.php, src/Twilio/Version.php, tests/Bootstrap.php, tests/Twilio/Holodeck.php, tests/Twilio/Request.php, tests/Twilio/Unit/ValuesTest.php
reverting #834 due to cluster test failure
=> chore: revert 'fix: avoid deprecation messages for PHP 8.4'

example/message.php, src/Twilio/Rest/Assistants/V1/Assistant/FeedbackModels.php, src/Twilio/Rest/Assistants/V1/Assistant/MessageModels.php, src/Twilio/Rest/Assistants/V1/AssistantModels.php, src/Twilio/Rest/Assistants/V1/KnowledgeModels.php, src/Twilio/Rest/Assistants/V1/ToolModels.php, src/Twilio/Rest/Content/V1/ContentModels.php, src/Twilio/Rest/Marketplace/V1/InstalledAddOn/InstalledAddOnUsageModels.php, src/Twilio/Rest/Marketplace/V1/ReferralConversionModels.php
Using correct model names while creating payload and JSON serialize()
=> chore: fix model names in json serialize and payload

src/Twilio/Rest/Accounts/V1/BulkConsentsList.php, src/Twilio/Rest/Accounts/V1/BulkContactsList.php, src/Twilio/Rest/Events/V1/SubscriptionList.php, src/Twilio/Rest/FlexApi/V1/PluginConfigurationList.php, src/Twilio/Rest/Proxy/V1/Service/SessionList.php, src/Twilio/Rest/Verify/V2/Service/Entity/ChallengeList.php
fix serialization for object array
=> chore: fix seralization

README.md
Updating readme for support of Oauth feature in the SDK
=> docs: update readme for oauth feature

README.md
twilio-php supports PHP 8.4 as well. Updating it in the README.md
=> docs: add php 8.4 in supported version

src/Twilio/Http/BearerToken/ApiTokenManager.php, src/Twilio/Http/BearerToken/OrgsTokenManager.php, src/Twilio/Rest/Oauth/V2/TokenList.php, src/Twilio/Rest/Oauth/V2/TokenOptions.php, tests/Twilio/ClusterTest.php
Changing token endpoint to oauth.twilio.com and using endpoint v2/token.
=> chore: change oauth token endpoint
