twilio/twilio-php

- Services/Twilio.php
The Lookups API is currently unusable with a range of confusing errors. Upon looking further, you're pointing it at the wrong endpoint.
> Correct the endpoint for the Lookups API

- Services/Twilio.php
- composer.json
If you install twillio-php through composer it seems to be impossible to access the Lookups_Services_Twilio class. This fix should now make it possible to grab it.
> Make Lookups_Services_Twilio available through composer.

- Services/Twilio/InstanceResource.php
- Services/Twilio/Rest/Call.php
- Services/Twilio/Rest/Message.php
This allows you to delete a message (or call) and makes this code work as expected:
https://github.com/twilio/twilio-php/commit/159960c415a7b296349d3b7e68ef788ca28d24b2#diff-74d2e3a0717d829d8824221b07bd8e5c
Note: This might be better implemented on the Message and Call objects as the delete() doesn't apply to all resources.
> Implemented message deleting

- docs/faq.rst
Missing final ) on $http = new Services_Twilio_TinyHttp()
> Fix syntax error

- .travis.yml
5.6 is current stable, so we should have that at the minimum. Since 7 is coming up we should check compatibility, and HHVM since a lot of people use it in production (but both should be allowed to fail).
> Add 5.6/7/HHVM allowing for appropriate failures

- Services/Twilio/CapabilityTaskRouter.php
- tests/CapabilityTaskRouterTest.php
- Allow fetching Reservations under a Worker by default
- Allow updating Reservations under a Worker
> Loading Reservations under a Worker by default in TaskRouter JS SDK

- Services/Twilio.php
- Services/Twilio/TaskRouter/Capability.php
- Services/Twilio/TaskRouter/CapabilityAPI.php
- Services/Twilio/TaskRouter/TaskQueue/Capability.php
- Services/Twilio/TaskRouter/Worker/Capability.php
- Services/Twilio/TaskRouter/Workspace/Capability.php
- tests/CapabilityTaskRouterTest.php
We need to directly reference CapabilityTaskRouter since this not follow the pattern of matching file name to matching class name.
> Twilio TaskRouter Capability autoload

- Twilio/Http/CurlClient.php
- Twilio/Tests/Unit/Http/CurlClientTest.php
Encode keys in the URL. Current version of the API supports parameter names with special characters. For example: 
* `StartTime>`
* `StartTime<`
> Encode parameter key

- Twilio/Twiml.php
If it was Twilio\Twiml, the class would have to be instantiated with Twilio\Twiml\Twiml which does not work with the autoloader.
> next-gen: The namespace should be Twilio, not Twilio\Twiml.

- Twilio/Tests/Unit/VersionTest.php
- Twilio/Version.php
* pageSize should be the smaller of the limit and the MAX_PAGE_SIZE
* pageSize should always be clamped to the MAX_PAGE_SIZE
* Test Suite with assertions about how `readLimits` should work.
> Fix readLimits logic for selecting best pageSize

- README.md
Issues:
1. SMS example has to/from swapped.
2. Voice example has to/from swapped.
3. SMS example needs to specify 'body' in lower case
4. Voice example needs array specifying 'url' and not a positional parameter
> Fix problems with code samples

- Twilio/Http/CurlClient.php
It can be difficult to see the raw traffic going over the wire, but that's what
you need to write tests that integrate with the twilio-php client - the kind
you use for all of your Holodeck tests!
This isn't *exactly* what goes over the wire, but it's close enough for the
purposes of testing this library. I tried setting CURLOPT_VERBOSE first, but
that prints a bunch of debugging information in addition to the actual data.
> Add env var to write raw HTTP traffic to stderr

- Services/Twilio/Capability.php
- Services/Twilio/TaskRouter/Capability.php
- Services/Twilio/TaskRouter/CapabilityAPI.php
- Services/Twilio/TaskRouter/TaskQueue/Capability.php
- Services/Twilio/TaskRouter/Worker/Capability.php
- Services/Twilio/TaskRouter/Workspace/Capability.php
- Readd include_once for dependencies
- Fix issue with redeclaring JWT.php due to separate directories now for TaskRouter vs. Client capability tokens.
> Fix TaskRouter Capability Tokens

- .travis.yml
This will cause our Travis build to report failure as soon as one of the version builds fails.
> Add fast_finish

- Twilio/Jwt/Grants/VoiceGrant.php
- Twilio/Tests/Unit/Jwt/AccessTokenTest.php
https://issues.corp.twilio.com/browse/CLIENT-4492
To support JS Clients per this spec:
https://paper.dropbox.com/doc/Proposal-FPA-Token-Format-for-Programmable-Voice-SDKs-xhdFHD6N3aPW9GRp4dXNX
> Add incoming.allow to AccessToken VoiceGrant

- Twilio/Rest/Sync/V1/Service/DocumentContext.php
- Twilio/Rest/Sync/V1/Service/SyncListContext.php
- Twilio/Rest/Sync/V1/Service/SyncMap/SyncMapItemContext.php
- Twilio/Rest/Sync/V1/Service/SyncMapContext.php
- Twilio/Rest/Sync/V1/Service/SyncStreamContext.php
- Twilio/Version.php
Hi there,
We have been actively integrating the Twilio API to our PHP structure in our company, and recently  startied to handling errors more efficiently for each of the services offered from the Rest client. However, an issue came up where the `TwilioException` thrown from the Twilio Sync Context was not being detected from our end.
This branch's purpose is to ensure all endpoints have the `@throws` PHP doc block in the functions where the `exception` function is referenced. The IDEs will then correctly spot the user of the `TwilioException` within the package code.
> Added @throws PHPDoc tags to Sync API Context and Version classes

- Twilio/Jwt/AccessToken.php
- Twilio/Jwt/ClientToken.php
- Twilio/Tests/Unit/Jwt/AccessTokenTest.php
- Twilio/Tests/Unit/Jwt/ClientTokenTest.php
Hi there.
I'm developing phone application and want to use the same JWT token across Twilio and my web API. In the current implementation, there is no ability to specify any custom claims.
Now I'm using my fork and it works fine:
```php
$tokenGenerator = Yii::$app->twilio->createClientToken();
$tokenGenerator->allowClientOutgoing(Yii::$app->params['twilio']['appSid']);
$tokenGenerator->addClaim('api-user', 'phone|' . $user->id);
return $tokenGenerator->generateToken();
```
I will be glad to see this functionality in the library.
> Ability to specify custom claims when creating ClientToken

- Twilio/Rest/Client.php
- Twilio/Tests/Unit/Rest/ClientTest.php
Add `validateSslCertificate` to check whether we can successfully make requests to the endpoint that uses the new SSL certificate
Note: `Client.php` is auto-generated; there'll be a separate PR for generating the new code.
> Add method to validate ssl certificate

- Twilio/Tests/Unit/TwiML/FaxResponseTest.php
- Twilio/Tests/Unit/TwiML/MessagingResponseTest.php
- Twilio/Tests/Unit/TwiML/VoiceResponseTest.php
- Twilio/TwiML/GenericNode.php
- Twilio/TwiML/TwiML.php
- Allow generic name for TwiML nodes
- Add tests for `MessagingResponse`, `VoiceResponse` and `FaxResponse`
> Allow adding TwiML children with generic tag names

- Twilio/Tests/Unit/TwiML/MessagingResponseTest.php
- Twilio/TwiML/TwiML.php
Added a test for mixed content, which uncovered a couple of related problems:
- There is no way to access generic nodes to add more children -- fixed the return value for `addChild`.
- The `addText` method is duplicative -- removed it. (This is technically a breaking change -- what do you all think?)
> Fixes for adding child nodes / text

- Twilio/Twiml.php
Steer folks towards the new `Twilio\TwiML` classes instead of `Twilio\Twiml`.
> Add deprecation warning to the old Twiml class

- Twilio/Security/RequestValidator.php
- Twilio/Tests/Unit/RequestValidatorTest.php
Our internal system sends the bodySHA256 parameter as hex, not base64, so this PR fixes that.
> Switch body validator to use hex instead of base64

- .travis.yml
Pin hhvm to 3.x because 4.x no longer supports composer.
We will need to follow developments here on hhvm if they introduce a new package manager and add support for that.
> Pin hhvm to pre-4.0 because of lack of composer support

- README.md
Twilio\Twiml is deprecated, so this just makes the readme easy to copy and paste the latest code w/o a deprecation warning.
> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.
> Update Readme TwiML Documentation

- composer.json
While we only officially support versions >=7.1 currently, we don't need to forcefully break older integrations.
> Loosen hard php version restriction

- CONTRIBUTING.md
- Dockerfile
- Dockerfile-dev
- Makefile
A fix per @childish-sambino's comment [here](https://github.com/twilio/twilio-php/commit/b415efdb41a6e48a95f9659001fca9f8121dcc5f#r34968353).
The docker-build command needs to pass in a version to work with the new Dockerfile format.
> Make docker-build work with new Dockerfile format

- composer.json
Follow up to #560 as version 5.6 of PHP requires a lower version of PHPUnit.
> Allow for usage of older PHP unit versions

- Makefile
Tests within Jenkins jobs currently fail because Jenkins don't support interactive terminals. This PR removes the interactive terminal
> Support running docker tests in Jenkins

- composer.json
This resolves an issue where we are failing tests on versions higher than 7.2.
> Dependency Fix for PHPUnit

- src/Twilio/Security/RequestValidator.php
- tests/Twilio/Unit/RequestValidatorTest.php
> added validation of signature without stripping port number

- src/Twilio/Http/CurlClient.php
An error occurred when I was using an HTTP / 1.0 proxy.
@see #575
> fix: Curl client now handles proxy responses over HTTP/1.0

- src/Twilio/Http/CurlClient.php
Fix: Fixing tunnels request. If you're setting proxy for `CurlClient`, It's not working since it's not handling `200 Tunnel established` header.
> fix: handle '200 Tunnel established header'

- src/Twilio/Http/GuzzleClient.php
- tests/Twilio/Unit/Http/GuzzleClientTest.php
- tests/Twilio/Unit/Jwt/ClientTokenTest.php
- tests/Twilio/Unit/Rest/ClientTest.php
> fix: only pass query option to Guzzle client if it is provided

- src/Twilio/Http/GuzzleClient.php
- tests/Twilio/Unit/Http/GuzzleClientTest.php
Guzzle defaults to using array-based POST parameters (e.g., `foo[]=1&foo[]=2`) instead of sending multiple values for the same key (e.g., `foo=1&foo=2`) which is what the Twilio API supports. This change builds body using the proper `application/x-www-form-urlencoded` type.
Fixes #649
> fix: support array parameters for Guzzle POSTs

- src/Twilio/Version.php
- tests/Twilio/Unit/VersionTest.php
Dropping the page limit calculation since it doesn't make sense to be calculated from a record limit.
Relates to https://github.com/twilio/twilio-python/pull/523
> fix: drop the page limit calculation

- src/Twilio/Jwt/AccessToken.php
- src/Twilio/Jwt/JWT.php
- tests/Twilio/Unit/Jwt/AccessTokenTest.php
This PR adds AccessTokenOptions.region parameter to support regional authentication. This value will be encoded in the twr header of the JWT. If the parameter is not specified or invalid, no twr value is added. See this document for more details.
JIRA: https://issues.corp.twilio.com/browse/CLIENT-8142
> feat: Add region to access token

- .gitignore
This makes sure `git clean -df` doesn't remove the `vendor` directory in librarian
> chore: ignore directory and not just the content

- src/Twilio/Serialize.php
- tests/Twilio/Unit/SerializeTest.php
Seeing issue on build system where UTC is showing as offset -0800. which is absurd.
> fix: use offset +0000 for iso8601 conversions

- tests/Twilio/Unit/SerializeTest.php
Found while testing the deploy in dev.
> fix: use offset +0000 for iso8601 conversion

- src/Twilio/Base/BaseClient.php
Creates BaseClient.php which has  handcrafted methods separated from Client.php 
> chore: create BaseClient in Base folder

- src/Twilio/Http/GuzzleClient.php
- tests/Twilio/Unit/Http/GuzzleClientTest.php
Updated Guzzle Client to support sending query params with multiple values for the same key (e.g. `foo=1&foo=2`) which is what the Twilio API supports. 
Fixes #752 
> fix: support array parameters for Guzzle GETs

- src/Twilio/Base/PhoneNumberCapabilities.php
- src/Twilio/Deserialize.php
- src/Twilio/Rest/Api/V2010/Account/AvailablePhoneNumberCountry/LocalInstance.php
- src/Twilio/Rest/Api/V2010/Account/AvailablePhoneNumberCountry/MachineToMachineInstance.php
- src/Twilio/Rest/Api/V2010/Account/AvailablePhoneNumberCountry/MobileInstance.php
- src/Twilio/Rest/Api/V2010/Account/AvailablePhoneNumberCountry/NationalInstance.php
- src/Twilio/Rest/Api/V2010/Account/AvailablePhoneNumberCountry/SharedCostInstance.php
- src/Twilio/Rest/Api/V2010/Account/AvailablePhoneNumberCountry/TollFreeInstance.php
- src/Twilio/Rest/Api/V2010/Account/AvailablePhoneNumberCountry/VoipInstance.php
- src/Twilio/Rest/Api/V2010/Account/IncomingPhoneNumber/LocalInstance.php
- src/Twilio/Rest/Api/V2010/Account/IncomingPhoneNumber/MobileInstance.php
- src/Twilio/Rest/Api/V2010/Account/IncomingPhoneNumber/TollFreeInstance.php
- src/Twilio/Rest/Api/V2010/Account/IncomingPhoneNumberInstance.php
- src/Twilio/Rest/Preview/HostedNumbers/AuthorizationDocument/DependentHostedNumberOrderInstance.php
- src/Twilio/Rest/Preview/HostedNumbers/HostedNumberOrderInstance.php
- src/Twilio/Rest/Proxy/V1/Service/PhoneNumberInstance.php
- src/Twilio/Rest/Proxy/V1/Service/ShortCodeInstance.php
- tests/Twilio/Unit/DeserializeTest.php
Type hint for $capabilities had been set as `string`, while [open_api_spec](https://github.com/twilio/twilio-oai/blob/main/spec/yaml/twilio_api_v2010.yaml#L431) specifies the type to be an `object` with boolean properties. 
Jira ticket: [link](https://issues.corp.twilio.com/browse/DII-790)
> fix: type hint for $capabilities to PhoneNumberCapabilities

- src/Twilio/Http/CurlClient.php
- tests/Twilio/Unit/Http/CurlClientTest.php
Earlier, we were setting contentType in curl client. So if contenttype is pre-set, it meant application/json. Since we are presetting each header now, we have corrected the check.
> chore: fix contentType check in post and put

- CHANGES.md
https://twilio-php.readthedocs.io/en/latest/ does not belong to Twilio anymore, so removing those links for security reasons.
> chore: remove urls that do not belong to Twilio anymore

- src/Twilio/Http/CurlClient.php
- tests/Twilio/Unit/Http/CurlClientTest.php
This PR addresses vulnerability that had no restriction for protocols that can be used by CurlClient.
This restricts it to `http` and `https`
> fix: updating client to only use http and https
